title:  Introducción a las probabilidades y  estadística 
description:  CM-274
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
  
<iframe width="560" height="315" src="https://www.youtube.com/watch?v=bxe2T-V8XRs" frameborder="0"> </iframe>
