\documentclass{article}
\usepackage[sc]{mathpazo}
\usepackage[T1]{fontenc}
\usepackage{bigints}
\usepackage[latin1]{inputenc}
\usepackage{geometry}
\usepackage{amsmath} 
\usepackage{mathtools}
%\usepackage[spanish]{babel}
\usepackage{latexsym}
\geometry{verbose,tmargin=1.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\usepackage{url}
\usepackage{graphicx}
%\theoremstyle{definition}
\everymath{\displaystyle}
\newtheorem{ejemplo}{{Ejemplo }}[section]
\newtheorem{defi}{{Definici\'on}}[section]
\newtheorem{pros}{{Proposici\'on}}[section]
\newtheorem{cor}{{Corolario}}[section]
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}
\hypersetup{
 pdfstartview={XYZ null null 1}}
\begin{document}

<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
library(ggplot2)
library(grid)
#library(animation)
# set global chunk options
opts_chunk$set(fig.path='figure/minimal-', fig.align='center', fig.show='hold')
options(formatR.arrow=TRUE,width=90)
@

%\title{\underline{\textbf{Notas de mat\'ematica}}}
%\date{}
%\maketitle
\hspace*{0.35\linewidth}
\begin{minipage}{0.6\linewidth}
Curso: Introducci\'on a la Probabilidad y Estad\'istica CM -274\par
Pr\'actica dirigida 3 Introducci\'on a la combinatoria\par 
\end{minipage}
\vspace{0.5cm}

%\maketitle
\textbf{\Large{Lista de ejercicios}}
%{\normalsize Los c\'odigos, se presentaran impresos,  o como un archivo con extensi\'on $.R$, mostrando ejemplos de su ejecuci\'on.}
\setlength{\unitlength}{1in}

\begin{picture}(6,.1) 
\put(0,0) {\line(1,0){6.25}}         
\end{picture}

\vspace{0.5cm}

\begin{enumerate}
\item Rose ha invitado a $n$ amigos a su fiesta de cumplea\~nos. Si todos asisten y cada uno le  da la mano a  todos los dem\'as invitados  en la fiesta exactamente una vez. ?`Cu\'al es el n\'umero de apretones de manos?.
\item ?` Cu\'antas matrices $n \times m$  con entradas $0$ o $1$ hay?.
\item ?`Cu\'antos n\'umeros de seis d\'igitos hay?. ?`Cu\'antos de ellos contienen el d\'igito 5?.
Ten en cuenta que el primer d\'igito de un n\'umero de $n$ d\'igitos es distinto de cero.

\item La poblaci\'on de una ciudad es de $20.000$ habitantes. Si cada residente tiene tres iniciales, ?` es cierto que al menos dos personas tienen las mismas iniciales?.

\item Supongamos que cuatro cartas se sacan sucesivamente de una baraja de $52$ cartas, con reemplazo y al azar. ?` Cu\'al es la probabilidad de sacar  al menos un rey?.

\item Se selecciona aleatoriamente un entero del conjunto $\{1, 2,\dots , 1,000, 000\}$. ?` Cu\'al es la probabilidad de que contenga el d\'igito 5?.

\item Al lanzar cuatro dados, ?` cu\'al es la probabilidad de lanzar, al menos  un 3?.


\item Se selecciona aleatoriamente un n\'umero del conjunto $\{0000, 0001, 0002,\dots, 9999\}$. ?` Cu\'al es la probabilidad de que la suma de los dos primeros d\'igitos del n\'umero seleccionado sea igual a la suma de sus dos \'ultimos d\'igitos?.

\item ?` Cu\'al es la probabilidad de que un n\'umero aleatorio de $r$ d\'igitos $(r \geq  3)$  contenga al menos un $0$, al menos un $1$ y al menos un 2?.

\item Una moneda  se lanza $10$ veces. ?` Cu\'al es la probabilidad de obtener exactamente tres caras?.

\item En el popular programa de televisi\'on \texttt{Who Wants to Be a Millionaire} se pide a los concursantes que clasifiquen   cuatro elementos de acuerdo con alguna norma: por ejemplo, puntos de referencia en  orden geogr\'afico, pel\'iculas en el orden de la fecha de lanzamiento, cantantes en el orden de fecha de nacimiento . ?` Cu\'al es la probabilidad de que un concursante pueda obtener la respuesta correcta s\'olo con adivinar?.
\item ?` Cuantas permutaciones del conjunto $\{a, b, c, d, e \}$ inicia con $a$ y termina en con $c$.
\item Robert tiene ocho invitados, dos de los cuales son Jim y John. Si llegan los invitados en un orden aleatorio, ?`cu\'al es la probabilidad de que John no llegue justo despu\'es de Jim?.

\item Un concurso de baile tiene $11$ competidores, de los cuales tres son estadounidenses, dos son mexicanos, tres rusos y tres italianos. Si el resultado del concurso s\'olo enumera la nacionalidad de los bailarines, ?` cu\'antos resultados son posibles?.

\item Se tiran seis dados. ?` Cu\'al es la probabilidad de que al menos dos de ellos muestren la misma cara?.
\item Un dado  se lanza ocho veces. ?` Cu\'al es la probabilidad de obtener  exactamente dos $3$, tres $1$ y tres $6$?.

\item Hay $12$ estudiantes en una clase. ?` Cu\'al es la probabilidad de que sus cumplea\~nos sean en $12$ meses diferentes?. Suponga que todos los meses tienen la misma probabilidad de incluir el cumplea\~nos de una persona seleccionada al azar.

\item Si ponemos cinco libros de matem\'aticas, seis de biolog\'ia, ocho de historia y tres de literatura en una estanter\'ia al azar, ?` cu\'al es la probabilidad de que todos los libros de matem\'aticas est\'en juntos?.

\item Si $n$  bolas se colocan aleatoriamente en $n$ cajas, ?` cu\'al es la probabilidad de que cada caja sea ocupada?.

\item Una ciudad tiene seis parques. Un s\'abado, seis compa\~neros de clase, que no son conscientes de la decisi\'on de cada uno, elegir un parque al azar y van all\'i al mismo tiempo. ?`  Cu\'al es la probabilidad de que al menos dos de ellos vayan al mismo parque?.

\item En una fiesta, $15$ parejas casadas est\'an sentadas al azar en una mesa redonda. ?`Cu\'al es la probabilidad de que todos los hombres est\'en sentados junto a sus esposas? Supongamos que de estas parejas casadas, cinco esposos y sus esposas tienen m\'as de $50$ a\~nos y los restantes maridos y esposas son todos menores de $50$ a\~nos. ?`Cu\'al es la probabilidad de que todos los hombres mayores de $50$ a\~nos est\'en sentados junto a sus esposas? Tenga en cuenta que cuando la gente est\'a sentada alrededor de una mesa redonda, s\'olo sus asientos en relativos  entre si importan. La posici\'on exacta de una persona no es importante. 
\item Una caja contiene cinco azules y ocho bolas rojas. Jim y Jack comienzan a sacar bolas de la caja, respectivamente, una a la vez, al azar y sin reemplazo hasta que se saque una bola azul. ?`Cu\'al es la probabilidad de que Jack saque la pelota azul?.

\item En una peque\~na ciudad, $11$ de los $25$ profesores tiene una opini\'on  en contra el aborto, ocho est\'an a favor  del aborto,y el resto son indiferentes. Se selecciona una muestra aleatoria de cinco profesores para una entrevista. 

\begin{enumerate}
\item ?`Cu\'al es la probabilidad de que todos ellos esten a favor  del aborto?.
\item ?`Cu\'al es la probabilidad de que todos ellos tengan  la misma opini\'on?.
\end{enumerate}

\item Sea $x$ un n\'umero positivo y sea $x_1 + x_2 + \cdots + x_k = n$ una ecuaci\'on. Un vector $(x_1, x_2, \dots, x_k)$ satisfaciendo  $x_1 + x_2 + \cdots + x_k = n$  se dice que es \texttt{una soluci\'on entera no negativa} de la ecuaci\'on si para cada $i, 1 \leq i \leq k$, $x_i$ es un entero no negativo. Se dice que es una \texttt{soluci\'on entera positiva} de la ecuaci\'on  si para cada $i, 1\leq i \leq k$, $x_i$ es un entero positivo. 

\begin{enumerate}
\item ?` Cu\'antas soluciones enteras no negativas distintas tiene la ecuaci\'on $x_1 + x_2 + \cdots + x_k = n$?.
\item ?` Cu\'antas soluciones enteras positivas distintas tiene la ecuaci\'on $x_1 + x_2 + \cdots  + x_k  = n$?.
\end{enumerate}


\item Un profesor distra\'ido escribi\'o $n$  cartas y las sell\'o en sobres antes de escribir las direcciones en los sobres. Luego escribi\'o las $n$ direcciones en los sobres al azar. ?` Cu\'al es la probabilidad de que por lo menos una carta fue dirigida correctamente?.

\item Jim tiene $20$ amigos. Si decide invitar a seis de ellos a su fiesta de cumplea\~nos, ?` cu\'antas opciones tiene?.

\item Una muestra aleatoria de $n$ elementos se toma de una poblaci\'on de tama\~no $N$ sin reemplazo. ?` Cu\'al es la probabilidad de que se incluya un elemento fijo de la poblaci\'on? Simplifique tu respuesta. 


\item Lili tiene $20$ amigos. Entre ellos est\'an Karen y Claude , que son marido y mujer. Lili quiere invitar a seis de sus amigos a su fiesta de cumplea\~nos. Si ni Karen ni Claude iran  a la fiesta si es que no van  con su pareja. ?` cu\'antas opciones tiene Lili?.

\item Prueba que $\binom{2n}{n} = \displaystyle \sum_{i = 0}^{n}\binom{n}{i}^2$.

\item Prueba que 

\[
\binom{n}{0} - \binom{n}{1} + \binom{n}{2} - \cdots + (-1)^k\binom{n}{k}+ \cdots + (-1)^n\binom{n}{n} = 0.
\]

\item Muestra que 

\[
\binom{n}{0} + \binom{n + 1}{1} + \cdots + \binom{n + r}{r} = \binom{n + r + 1}{r}.
\]

\item Por una argumento combinatorio, prueba que $r \leq n$ y $r \leq m$,

\[
\binom{n + m}{r} = \binom{m}{0}\binom{n}{r} + \binom{m}{1}\binom{n}{r - 1} + \cdots + \binom{m}{r}\binom{n}{0}.
\]

\item Evalua la siguiente suma:

\[
\binom{n}{0} + \frac{1}{2}\binom{n}{1} + \frac{1}{3}\binom{n}{2}+ \cdots + \frac{1}{n + 1}\binom{n}{n}.
\]


\item Aproxima el valor de $[2^n(n!)^2]/(2n)!$ cuando $n \rightarrow \infty$.

\item Supongamos que lanzamos una moneda  $2n$ veces. ?` Cu\'al es la probabilidad de que salgan un igual n\'umero de caras y sellos?.
\item Frente a la oficina de Jeff hay un estacionamiento con $13$ plazas de aparcamiento en una fila. Cuando los coches llegan a este aparcamiento, se estacionan aleatoriamente en uno de los lugares vac\'ios. Jeff estaciona su coche en el \'unico lugar vac\'io que queda, luego se va a su oficina. A su regreso encuentra que hay siete plazas vac\'ias. Si no ha estacionado su coche en un  extremo del  estacionamiento, ?` cu\'al es la probabilidad de que ambos espacios de estacionamiento que est\'an al lado del auto de Jeff est\'en vac\'ios?.


\item Un dado es lanzado seis veces. ?` Cu\'al es la probabilidad de obtener exactamente dos 6?.
\item Se selecciona al azar un n\'umero de cuatro d\'igitos. ?` Cu\'al es la probabilidad de que el  lugar de la unidades, sea menor que el lugar de las  decenas, el lugar de las  decenas sea  menor que el lugar de las  centenas y el  lugar de las centenas  sea menor que el  lugar de los miles? Ten en cuenta que el primer d\'igito de un n\'umero de $n$ d\'igitos es distinto de cero.

\item Una baraja ordinaria de $52$ tarjetas se reparte  $13$ cartas  a cuatro jugadores al azar. ?` Cu\'al es la probabilidad de que cada jugador reciba $13$ cartas del mismo tipo (suite)?.

\item Un tren consta de $n$ coches. Cada uno de los $m$ pasajeros $(m > n)$ elegir\'a un coche al azar. ?` Cu\'al es la probabilidad de que (a) haya al menos un pasajero en cada carro,  (B) exactamente haya  $r (r <n)$ carros que permanezcan desocupados?.

\item Sea $n$ un entero positivo. Una muestra aleatoria de cuatro elementos es escogida del conjunto  $ \{0, 1, 2, \dots,  N$, uno a la vez y con reemplazo. ?` Cu\'al es la probabilidad de que la suma de los dos primeros elementos sea igual a la suma de los dos \'ultimos elementos?.

\item Una moneda  se lanza $n$ veces. Calcula la probabilidad de no obtener caras sucesivas.

\item (Problema de Newton-Pepys). Isaac Newton fue consultado sobre el siguiente problema de Samuel Pepys, que quer\'ia la informaci\'on con prop\'osito de juego de apuestas.?` Cu\'al de los siguientes eventos tiene la probabilidad m\'as alta?,

\begin{verbatim}

  A : Al menos un 6 aparece cuando se hacen rodar 6 dados.
  B : Por lo menos dos 6 aparecen cuando 12 dados  son rodados
  c : Al menos tres 6 aparecen cuando se hacen rodar 18 .

\end{verbatim}

\item (Bose -Einstein)?` Cu\'antas maneras hay de elegir $k$ veces de un conjunto de $n$ objetos con reemplazo, si el orden no importa (s\'olo nos preocupamos por cu\'antas veces se eligi\'o cada objeto, no el orden en que fueron elegidos)?.

\item (Problema de correspondencia de Montmort) Considere una baraja  de $n$ cartas,  etiquetadas de $1$ a $n$. Tiramos las cartas una a una, diciendo  los n\'umeros $1$ a $n$ cuando lo hagas. Ganamos el juego si en alg\'un momento, el n\'umero que se dice en voz alta es el mismo en la carta  que se voltea. ?`Cu\'al es la probabilidad de ganar?.
\end{enumerate}

\end{document} 

